import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="pl-8">
        <span className="font">^</span>{" "}
        <i className="ml-2">
          A handful of interactive demos that highlight my practical skills with
          algorithms and UI development.
        </i>
      </div>
      <div className="mt-4 pl-8">
        <i className="ml-6">
          Made by{" "}
          <a
            href="https://matts-projects.vercel.app/projects"
            className="text-blue-500 hover:text-blue-700 underline"
          >
            Matthew
          </a>
        </i>
      </div>
    </>
  );
};

export default Home;
